---
  key: '<can setup in env var>'  # WARNING do not commit your API key in a public repo! The -k or --key option can also be used to set the meetup API key
  name: 'SydEthereum'     # is the Meetup name which is the urlname in the Meetup API