---
  wshost: "localhost"
  wsport: "8647"
#  contractAddress: '0x414bA2D0a0B09b691B51bb7Aa5BFFdA416453e67' # Dev
  contractAddress: '0xa82490c21A2c924e5C0a759E8cA6a165FCa8dce1' # Main net
#  contractOwner: '0x8ae386892b59bd2a7546a9468e8e847d61955991' # Dev
  contractOwner: '0xCfF644e86Ca1E0212288BcC4ff36Ae9a47714bbc' # Main net
  symbol: 'SET'
  tokenName: 'Transferable Sydney Ethereum Token'
  issueAmounts:
    newMember: 1000
    attendEvent: 2000
    speakAtEvent: 3000
    hostEvent: 5000
    sponsorEvent: 10000