---
  url: "ws://localhost:8647"
  contractAddress: '0xA45125D4eCb367ccD4C626ACFfB355CC4A96a32a' # Dev geth
#  contractAddress: '' # Dev Parity
  contractOwner: '0x8ae386892b59bd2a7546a9468e8e847d61955991' # Dev geth
  symbol: 'SET'
  tokenName: 'Transferable Sydney Ethereum Token'
  issueAmounts:
    newMember: 1000
    attendEvent: 2000
    speakAtEvent: 3000
    hostEvent: 5000
    sponsorEvent: 10000