---
  wshost: "mainnet.infura.io/ws"
  wsport: "443" # Infura
#  wsport: "999" # Infura
  contractAddress: '0xe06eda7435bA749b047380CEd49121ddE93334Ae' # Main net
  contractAddressBlock: 4219770 # prod
  contractOwner: '0xCfF644e86Ca1E0212288BcC4ff36Ae9a47714bbc' # Main net
  symbol: 'SET'
  tokenName: 'Transferable Sydney Ethereum Token'
  issueAmounts:
    newMember: 1000
    attendEvent: 2000
    speakAtEvent: 3000
    hostEvent: 5000
    sponsorEvent: 10000