---
  wshost: "localhost"
  wspost: "8647"
  contractAddress: '0xA771E3Aaaf481F439Fcc89c640a8282aCB1Efe6A'
  contractOwner: '0x8ae386892b59bd2a7546a9468e8e847d61955991'
  symbol: 'SET'
  tokenName: 'Transferrable Sydney Ethereum Token'
