---
  providerType: "jsonrpc"
  providerParam1: "http://localhost:8646"
  providerParam2: true  # testing
  providerParam3: 100   # ChainId 100 = 0x64
  contractAddress: '0xA45125D4eCb367ccD4C626ACFfB355CC4A96a32a' # Dev Parity
  contractOwner: '0x8Ae386892b59bD2A7546a9468E8e847D61955991'
  symbol: 'SET'
  tokenName: 'Transferable Sydney Ethereum Token'
  issueAmounts:
    newMember: 1000
    attendEvent: 2000
    speakAtEvent: 3000
    hostEvent: 5000
    sponsorEvent: 10000