---
  url: "ws://localhost:8647"
  contractAddress: '0xA45125D4eCb367ccD4C626ACFfB355CC4A96a32a'
#  contractAddress: '' # Dev Parity
  contractOwner: '0x8Ae386892b59bD2A7546a9468E8e847D61955991'
  symbol: 'SET'
  tokenName: 'Transferable Sydney Ethereum Token'
  issueAmounts:
    newMember: 1000
    attendEvent: 2000
    speakAtEvent: 3000
    hostEvent: 5000
    sponsorEvent: 10000