---
  wshost: "localhost"
  # port of the websocket connection
  wsport: "8647"

  contractAddress: '0xADfFb1B32A476167A0BF387e8aaE314ee437c3F7' # Dev
#  contractAddress: '0xe06eda7435bA749b047380CEd49121ddE93334Ae' # Main net

  contractOwner: '0x8ae386892b59bd2a7546a9468e8e847d61955991' # Dev
#  contractOwner: '0xCfF644e86Ca1E0212288BcC4ff36Ae9a47714bbc' # Main net

  # the block the contract was deplyed in.
  # This defaults to 0 if not set which makes getting the contract events slower as it has to scan the whole blockchain
#  contractAddressBlock: 4219770

  symbol: 'SET'
  tokenName: 'Transferable Sydney Ethereum Token'

  # The default amount of tokens to be issued
  issueAmounts:
    newMember: 1000
    attendEvent: 2000
    speakAtEvent: 3000
    hostEvent: 5000
    sponsorEvent: 10000