[parity]
mode = "last"

chain = "MeetupChain"
base_path = "/Users/nicholasaddison/Documents/workspaces/meetup-token/testchain/parity"
db_path = "/Users/nicholasaddison/Documents/workspaces/meetup-token/testchain/parity/chains"
keys_path = "/Users/nicholasaddison/Documents/workspaces/meetup-token/testchain/keystore"

[websockets]
disable = false
port = 8647
interface = "local"
origins = ["none"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["none"]

[ui]
force = false
disable = false
port = 8181
interface = "127.0.0.1"
path = "$HOME/Library/Application Support/io.parity.ethereum/signer"

[ipc]
disable = true

[dapps]
disable = true

[secretstore]
disable = true

[ipfs]
enable = false

[vm]
jit = false

[misc]
logging = "own_tx=trace"
log_file = "/Users/nicholasaddison/Documents/workspaces/meetup-token/testchain/parity/parity.log"
color = true